language: node_js
node_js:
  - 10
jobs:
  include:
    - stage: pull_request
      if: type IN (pull_request)
      env:
        - ARTIFACT_ID=$TRAVIS_PULL_REQUEST
      script:
        - npm install
        - npm run -s bootstrap

    - stage: build_branch
      if: NOT tag IS present AND type IN (push) AND NOT branch =~ ^sprint-*
      env:
        - ARTIFACT_ID=$TRAVIS_COMMIT
      script:
        - npm install
        - npm run -s bootstrap

    - stage: continuous_integration
      if: NOT tag IS present AND type IN (push) AND branch =~ ^sprint-*
      env:
        - ARTIFACT_ID=$TRAVIS_COMMIT
      script:
        - npm install
        - npm run -s bootstrap

    - stage: release
      if: tag IS present
      env:
        - ARTIFACT_ID=$TRAVIS_COMMIT
        - RELEASE_VERSION=$TRAVIS_TAG
      script:
        - npm install
        - npm run -s bootstrap
