language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: pull_request
      if: type IN (pull_request)
      env:
        - ARTEFACT_ID=$TRAVIS_PULL_REQUEST
      script:
        - npm run -s bootstrap
        - npm run -s test
        - npm run -s build

    - stage: build_branch
      if: NOT tag IS present AND type IN (push) AND NOT branch =~ ^sprint-*
      env:
        - ARTEFACT_ID=$TRAVIS_COMMIT
      script:
        - npm run -s bootstrap
        - npm run -s test
        - npm run -s build

    # - stage: continuous_integration
    #   if: NOT tag IS present AND type IN (push) AND branch =~ ^sprint-*
    #   env:
    #     - ARTEFACT_ID=$TRAVIS_COMMIT
    #   script:
        

    # - stage: release
    #   if: tag IS present
    #   env:
    #     - ARTEFACT_ID=$TRAVIS_COMMIT
    #     - RELEASE_VERSION=$TRAVIS_TAG
    #   script:
    #     - 
